#!/bin/bash

source $PWD/nova_env.sh

mysql -h$DB_HOST -p$DB_PASS -u$DB_USER -e "CREATE DATABASE IF NOT EXISTS $NOVA_API_DBNAME;"
mysql -h$DB_HOST -p$DB_PASS -u$DB_USER -e "CREATE DATABASE IF NOT EXISTS $NOVA_DBNAME;"
mysql -h$DB_HOST -p$DB_PASS -u$DB_USER -e "GRANT ALL PRIVILEGES ON \
        $NOVA_API_DBNAME.* TO '$NOVA_DBUSER'@'$DB_HOST' IDENTIFIED BY '$NOVA_DBPASS';"
mysql -h$DB_HOST -p$DB_PASS -u$DB_USER -e "GRANT ALL PRIVILEGES ON \
        $NOVA_API_DBNAME.* TO '$NOVA_DBUSER'@'%' IDENTIFIED BY '$NOVA_DBPASS';"
mysql -h$DB_HOST -p$DB_PASS -u$DB_USER -e "GRANT ALL PRIVILEGES ON \
        $NOVA_DBNAME.* TO '$NOVA_DBUSER'@'$DB_HOST' IDENTIFIED BY '$NOVA_DBPASS';"
mysql -h$DB_HOST -p$DB_PASS -u$DB_USER -e "GRANT ALL PRIVILEGES ON \
        $NOVA_DBNAME.* TO '$NOVA_DBUSER'@'%' IDENTIFIED BY '$NOVA_DBPASS';"
