#!/usr/bin/bash

NOVA_DBNAME=nova
NOVA_DBUSER=nova
NOVA_API_DBNAME=nova_api
NOVA_PASS=redhat
NOVA_DBPASS=redhat
DB_HOST=127.0.0.1
DB_USER=root
DB_PASS=root
RABBIT_PASS=redhat
RABBIT_USER=openstack
RABBIT_HOST=127.0.0.1
