#!/bin/bash

source $PWD/keystone_env.sh

mysql -p$DB_PASS -u $DB_USER -e "CREATE DATABASE IF NOT EXISTS $KEYSTONE_DBNAME;"
mysql -p$DB_PASS -u $DB_USER -e "GRANT ALL PRIVILEGES ON $KEYSTONE_DBNAME.* TO '$KEYSTONE_DBUSER'@'localhost' \
  IDENTIFIED BY '$KEYSTONE_DBPASS';"
mysql -p$DB_PASS -u $DB_USER -e "GRANT ALL PRIVILEGES ON $KEYSTONE_DBNAME.* TO '$KEYSTONE_DBUSER'@'%' \
  IDENTIFIED BY '$KEYSTONE_DBPASS';"

