#!/bin/bash

source $PWD/glance_env.sh

mysql -h$DB_HOST -p$DB_PASS -u$DB_USER -e "CREATE DATABASE IF NOT EXISTS $GLANCE_DBNAME;"
mysql -h$DB_HOST -p$DB_PASS -u$DB_USER -e "GRANT ALL PRIVILEGES ON $GLANCE_DBNAME.* TO '$GLANCE_DBUSER'@'localhost' \
  IDENTIFIED BY '$GLANCE_DBPASS';"
mysql -h$DB_HOST -p$DB_PASS -u$DB_USER -e "GRANT ALL PRIVILEGES ON $GLANCE_DBNAME.* TO '$GLANCE_DBUSER'@'%' \
  IDENTIFIED BY '$GLANCE_DBPASS';"
